"""Roles table and models separate file

Revision ID: ef05b0bea680
Revises: 6fd83ca2c939
Create Date: 2024-04-20 20:39:10.018897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef05b0bea680'
down_revision = '6fd83ca2c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=True),
    sa.Column('admin_panel', sa.Boolean(), nullable=True),
    sa.Column('form_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('role'),
    sa.UniqueConstraint('role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
